variables:
    TUTOR_PLUGIN: themetdr
    TUTOR_EXTRA_ENABLED_PLUGINS: mfe
    TUTOR_PYPI_PACKAGE: tutor-themetdr
    TUTOR_IMAGES: openedx mfe
    GITHUB_REPO: epfl-cede/tutor-themetdr

include:
  - project: 'community/tutor-ci'
    file: 'plugin-gitlab-ci.yml'
